application: dictatorornot
version: 1
runtime: go
api_version: go1

handlers:

- url: /dictatorornot.min.js
  static_files: dist/dictatorornot.min.js
  upload: dist/dictatorornot.min.js

- url: /style.css
  static_files: dist/style.css
  upload: dist/style.css

- url: /
  static_files: dist/index.html
  upload: dist/index.html


skip_files:
- bower_components
- node_modules
